name: 'JetBrains Plugin Platform Version Update Action'
description: 'GitHub Action to update JetBrains Plugins when a new JetBrains Platform Version is available.'
author: 'ChrisCarini'
inputs:
  PAT_TOKEN_FOR_IJ_UPDATE_ACTION: # change this
    required: true
    description: 'PAT token; necessary to update workflow files.'
runs:
  using: 'node16'
  main: 'dist/index.js'
