# `dist/index.js` is a special file in Actions.
# When you reference an action with `uses:` in a workflow,
# `index.js` is the code that will run.
# For our project, we generate this file through a build process from other source files.
# We need to make sure the checked-in `index.js` actually matches what we expect it to be.
name: Check dist/

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  check-dist:
    name: Check dist/
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        if: ${{ github.event_name != 'pull_request' }}
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        if: ${{ github.event_name == 'pull_request' }}
        with:
          # ref: ${{ github.event.pull_request.head.ref }}
          # repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_PAT_REPO_WORKFLOW_SCOPE }}

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: install
        run: npm ci

      - name: Rebuild the dist/ directory
        run: |
          npm run bundle

      - name: Compare the expected and actual dist/ directories
        run: |
          if [ "$(git diff --ignore-space-at-eol dist/ | wc -l)" -gt "0" ]; then
            echo "Detected uncommitted changes after build.  See status below:"
            git diff
            exit 1
          fi
        id: diff

      - name: Push changes back to PR branch
        if: ${{ failure() && steps.diff.outcome == 'failure' && github.event_name == 'pull_request' }}
        run: |
          git config --global user.email "6374067+ChrisCarini@users.noreply.github.com"
          git config --global user.name "ChrisCarini"
          git add ./dist/
          git commit -m 'fixing dist'
          git push

      # If index.js was different than expected, upload the expected version as an artifact
      - uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        if: ${{ failure() && steps.diff.outcome == 'failure' }}
        with:
          name: dist
          path: dist/
